development:
  adapter: postgresql
  encoding: utf8
  database: pagliacci_development
  host: localhost
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: pagliacci_test
  host: localhost
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: pagliacci_production
  host: localhost
  pool: 5
  username:
  password:
